version: "3.8"

services:
  robot_app:
    build: "."
    command: gunicorn --bind 0.0.0.0:4200 robot_app:app
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - nginx_network
      - database_network

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - database_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - nginx_network
    depends_on:
      - robot_app

networks:
  nginx_network:
    name: nginx_network
    driver: bridge
  database_network:
    name: database_network
    driver: bridge

volumes:
  postgres_data:
